version: "3.4"

services:
  app:
    image: golang:1.14
    working_dir: /app
    depends_on:
      - database
    volumes:
      - .:/app
      - pkg:/go/pkg
    ports:
      - "5411:5411"
    env_file:
      - _env
    command: ["go", "run", "cmd/jivala-core/main.go"]

  database:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=jivala-core
    ports:
      - "5432:5432"

  migration:
    image: "migrate/migrate"
    depends_on:
      - database
    volumes:
      - ./resources/migrations:/migration
    env_file:
      - _env
    command: -path /migration -database postgres://dbuser:dbpass@database:5432/jivala-core?sslmode=disable -verbose up

volumes:
  pkg: