apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: ghanto/jivala-core
          ports:
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: postgres-config